const data = [
  {
    faculty: 'Факультет бизнес-администрирования',
    year: '2020',
    form: 'дневная ',
    course: '1',
    number: '001',
    speciality: 'Менеджмент',
    entranceyear: '2020',
    filename: '001.xml',
    xls: '001.xlsx',
  },
  {
    faculty: 'Факультет бизнес-администрирования',
    year: '2020',
    form: 'дневная ',
    course: '1',
    number: '002',
    speciality: 'Менеджмент',
    entranceyear: '2020',
    filename: '002.xml',
    xls: '002.xlsx',
  },
  {
    faculty: 'Факультет бизнес-администрирования',
    year: '2020',
    form: 'дневная ',
    course: '1',
    number: '011',
    speciality: 'Бизнес-администрирование',
    entranceyear: '2020',
    filename: '011.xml',
    xls: '011.xlsx',
  },
  {
    faculty: 'Факультет бизнес-администрирования',
    year: '2020',
    form: 'дневная ',
    course: '1',
    number: '012',
    speciality: 'Бизнес-администрирование',
    entranceyear: '2020',
    filename: '012.xml',
    xls: '012.xlsx',
  },
  {
    faculty: 'Факультет бизнес-администрирования',
    year: '2020',
    form: 'дневная ',
    course: '1',
    number: '013 (Engl)',
    speciality: 'Бизнес-администрирование',
    entranceyear: '2020',
    filename: '013.xml',
    xls: '013.xlsx',
  },
  {
    faculty: 'Факультет бизнес-администрирования',
    year: '2020',
    form: 'дневная ',
    course: '1',
    number: '014 (Engl)',
    speciality: 'Бизнес-администрирование',
    entranceyear: '2020',
    filename: '014.xml',
    xls: '014.xlsx',
  },
  {
    faculty: 'Факультет бизнес-администрирования',
    year: '2020',
    form: 'дневная ',
    course: '1',
    number: '015 (Engl)',
    speciality: 'Бизнес-администрирование',
    entranceyear: '2020',
    filename: '015.xml',
    xls: '015.xlsx',
  }
];

export default data;
